services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"  # Para el visualizador de Redis Stack
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  streamlit_app:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./docker_secrets.toml:/app/.streamlit/secrets.toml
    environment:
      - ENV=production
    env_file:
      - .env
    command: streamlit run app.py